

source("get_CI.R")

s_sample <- function(u, theta) {
  # Extract the mean (location) and std. dev (scale) from theta
  mean <- theta[1]
  sd <- theta[2]
  
  # Determine the number of samples and dimensions from the seed matrix u
  # are determined from the `u` matrix.
  num_samples <- nrow(u)
  num_dimensions <- ncol(u)
  
  # Initialize a matrix to store the samples
  samples <- matrix(0, nrow = num_samples, ncol = num_dimensions)
  
  # Generate samples from a location-scale normal distribution for each dimension 
  # loop iterates over each dimension, generating set of random nums. from a normal distribution 
  # w/  specified mean and std. dev.for that dimension. 
  # These nums are then added to the `samples` matrix.
  for (i in  1 : num_samples) {
    samples[i,] <- qnorm(u[i,], mean = mean, sd = sd/sqrt(100)) # input sample size
  }
  
  return(samples) # matrix of simulated samples returned
}

sample_size <- 100 # sample size
R <- 200 # Repro sample size R
alpha <- .05 # significance level
tol <- 10^-4

# population parameters
mu <- 1
sigma <- 1

seeds <- matrix(data = runif(R)) # 200 pre-generated seeds

# generate 50 normal samples based on the population mean and sd
data <- rnorm(n = sample_size,
              mean = mu,
              sd = sigma)

s_obs <- mean(data)

# unit testing
repro_data <- s_sample(seeds, c(mu, sigma))
plot(density(repro_data), lwd = 2)

p_value(c(-10, 0.999), c(-1, 1), seeds, s_sample, s_obs)
accept(alpha, c(-10, 0.999), c(-1, 1), seeds, s_sample, s_obs)

# this is the classical way of finding the confidence interval for mu
normal_CI <- function(data, alpha) {
  z <- qnorm(1 - alpha/2)
  x_bar <- mean(data)
  sample_size <- length(data)
  half_width <- z/sqrt(sample_size)
  interval <- c(x_bar - half_width, x_bar + half_width)
  
  return(interval)
}

classical_CI <- normal_CI(data, alpha)

# this is the confidence interval generated by Repro sampling
Repro_CI <- get_CI(alpha, c(-10, 0.999), c(10, 1), 1, seeds, s_sample, s_obs, tol)

Repro_CI2 <- get_CI2(alpha, c(-10, 0.999), c(10, 1), 1, seeds, s_sample, s_obs, tol)

Repro_CI2 - Repro_CI
