

source("s_sample.R")
source("p_val.R")
source("get_CI.R")


sample_size <- 100 # sample size
n <- 100 # sample size
R <- 200 # Repro sample size R
alpha <- .05 # significance level
tol <- 10^-4

# population parameters
mu <- 1
sigma <- 1

seeds <- matrix(data = runif(R)) # 200 pre-generated seeds

# generate 50 normal samples based on the population mean and sd
data <- rnorm(n = sample_size,
              mean = mu,
              sd = sigma)

s_obs <- mean(data)

# unit testing
repro_data <- s_sample(seeds, c(mu, sigma))
plot(density(repro_data), lwd = 2)

accept(alpha, c(2,0.5), c(10,2), seeds, s_sample, s_obs)
p_value(c(1,0.3), c(10,20), seeds, s_sample, s_obs)

# this is the classical way of finding the confidence interval for mu
normal_CI <- function(data, alpha) {
  z <- qnorm(1 - alpha/2)
  x_bar <- mean(data)
  sample_size <- length(data)
  half_width <- z/sqrt(sample_size)
  interval <- c(x_bar - half_width, x_bar + half_width)
  
  return(interval)
}

classical_CI <- normal_CI(data, alpha)

# this is the confidence interval generated by Repro sampling
Repro_CI <- get_CI(alpha, c(-10,0), c(10,10), 1, seeds, s_sample, s_obs, tol)



