

#' confidence_grid
#'
#' returns the indicator array
#'
#' @param alpha Significance level.
#' @param lower_bds Vector containing the lower bounds for the search space.
#' @param upper_bds Vector containing the upper bounds for the search space
#' @param seeds Seeds containing all the randomness.
#' @param G Data generating process.
#' @param s_obs Observed statistic.
#' @param tol tolerance of the confidence interval.
#' @param res resolution of the grid
#' @param t_init Starting point for the initial search.
#' @param T_stat A distance metric, default to Mahalanobis distance.
#' @return A list containing ind_array, updated_lower_bds, and updated_upper_bds.
#' @examples
#' ### Regular normal
#' set.seed(123)
#' n <- 100 # sample size
#' R <- 200 # Repro sample size
#' alpha <- .05 # significance level
#' tol <- 1e-4 # tolerance for the confidence set
#' s_obs <- c(1.12, 0.67) # the observed sample mean
#' seeds <- matrix(rnorm(R * (n + 2)), nrow = R, ncol = n + 2) # pre-generated seeds
#'
#' # this function computes the repro statistics given the seeds and the parameter
#' s_sample <- function(seeds, theta) {
#'   # generate the raw data points
#'   raw_data <- theta[1] + sqrt(theta[2]) * seeds[, 1:n]
#'
#'   # compute the regular statistics
#'   s_mean <- apply(raw_data, 1, mean)
#'   s_var <- apply(raw_data, 1, var)
#'
#'   return(cbind(s_mean, s_var))
#' }
#'
#' lower_bds <- c(-5, 0.01) # lower bounds for the parameter search region
#' upper_bds <- c(5, 5) # upper bounds for the parameter search region
#'
#' res = 10  # resolution of the grid
#' result <- confidence_grid(alpha, lower_bds, upper_bds, seeds, s_sample, s_obs, tol, res)
#' print(result$ind_array)
#' print(result$updated_lower_bds)
#' print(result$updated_upper_bds)
#'
#' @export

confidence_grid <- function(alpha, lower_bds, upper_bds, seeds, G, s_obs, tol, res, t_init = NULL, T_stat = ma_depth) {

  # for each parameter, run the get_CI function to obtain a confidence interval
  updated_lower_bds <- lower_bds
  updated_upper_bds <- upper_bds

  p <- length(lower_bds)
  for (j in 1:p) {
    confidence_interval <- get_CI(alpha, lower_bds, upper_bds, j, seeds, G, s_obs, tol, t_init, T_stat)
    updated_lower_bds[j] <- confidence_interval[1]
    updated_upper_bds[j] <- confidence_interval[2]
  }

  # resolution gives the number of divisions for each parameter, divide by res to get the grid width
  grid_width <- (updated_upper_bds - updated_lower_bds) / res

  # an array representing whether or not a grid contains an accepted value
  indicator_array <- array(rep(0, res ** p), dim = rep(res, p))

  # given the indices, this function search the corresponding cube and update the indicator array
  update_array <- function(indices, indicator_array) {
    cube_lower_bds <- updated_lower_bds + (indices - 1) * grid_width
    cube_upper_bds <- cube_lower_bds + grid_width
    mid_point <- (cube_lower_bds + cube_upper_bds) / 2

    if (p_value(cube_lower_bds, cube_upper_bds, seeds, G, s_obs, mid_point, T_stat)$p_val > alpha) {
      indicator_array <- do.call('[<-', c(list(indicator_array), as.list(indices), 1))
    }

    return(indicator_array)
  }

  # function that recursively loops through all sub-divided cubes,
  loop_thru <- function(curr_pos, indicator_array, former_indices = c()) {
    if (curr_pos <= p) {
      for (i in 1:res) {
        new_indices <- c(former_indices, i)
        indicator_array <- loop_thru(curr_pos + 1, indicator_array, new_indices)
      }
    } else {
      indicator_array <- update_array(former_indices, indicator_array)
    }
    return(indicator_array)
  }

  indicator_array <- loop_thru(1, indicator_array)

  return(list(ind_array = indicator_array,
              updated_lower_bds = updated_lower_bds,
              updated_upper_bds = updated_upper_bds))
}

#' grid_projection
#'
#' Projects the multidimensional indicator array generated by confidence_grid down to 2d for visualization
#'
#' @param indicator_array Indicator array generated using confidence_grid
#' @param index_set A vector containing the indices representing the reduced dimension
#' @return A two-dimensional indicator array ready for visualization.
#' @examples
#' ### simple projection
#' ind_arr <- array(c(1, 0, 0, 0, 0, 1, 0, 1), dim = rep(2, 3))
#' print(ind_arr)
#' # project this indicator array onto a 2d subspace by first and second dimension
#' ind_arr_12 <- grid_projection(ind_arr, c(1,2))
#' print(ind_arr_12)
#' ind_arr_13 <- grid_projection(ind_arr, c(1,3))
#' print(ind_arr_13)
#' ind_arr_23 <- grid_projection(ind_arr, c(2,3))
#' print(ind_arr_23)
#' @export

# this function computes the projection of the indicator_array onto 2d or 1d arrays
grid_projection <- function(indicator_array, index_set) {
  if (length(index_set) == 1 | length(index_set) == 2) {
    return(apply(indicator_array, index_set, function(x) as.integer(any(x==1))))
  } else {
    print("A vector of length 1 or 2 is expected for the second input.")
  }
}


#' plot_grid
#'
#' projects the indicator array generated by confidence_grid down to 2d for visualization
#'
#' @param indicator_array Indicator array generated using confidence_grid
#' @param lower_bds Vector containing the lower bounds for the search space.
#' @param upper_bds Vector containing the upper bounds for the search space.
#' @return A grid plot showing the confidence regions
#' @examples
#' # Regular normal
#' set.seed(123)
#' n <- 100 # sample size
#' R <- 200 # Repro sample size
#' alpha <- .05 # significance level
#' tol <- 1e-4 # tolerance for the confidence set
#' s_obs <- c(1.12, 0.67) # the observed sample mean
#' seeds <- matrix(rnorm(R * (n + 2)), nrow = R, ncol = n + 2) # pre-generated seeds
#'
#' # this function computes the repro statistics given the seeds and the parameter
#' s_sample <- function(seeds, theta) {
#'   # generate the raw data points
#'   raw_data <- theta[1] + sqrt(theta[2]) * seeds[, 1:n]
#'
#'   # compute the regular statistics
#'   s_mean <- apply(raw_data, 1, mean)
#'   s_var <- apply(raw_data, 1, var)
#'
#'   return(cbind(s_mean, s_var))
#' }
#'
#' lower_bds <- c(-5, 0.01) # lower bounds for the parameter search region
#' upper_bds <- c(5, 5) # upper bounds for the parameter search region
#'
#' res = 20  # resolution of the grid
#' result <- confidence_grid(alpha, lower_bds, upper_bds, seeds, s_sample, s_obs, tol, res)
#'
#' ind_arr <- result$ind_array
#' lower_bds <- result$updated_lower_bds
#' upper_bds <- result$updated_upper_bds
#' print(ind_arr)
#' plot_grid(ind_arr, lower_bds, upper_bds)
#' print(lower_bds)
#' print(upper_bds)
#'
#' @import ggplot2
#' @export

# given the grid_projection (1d or 2d) and the bounds, this functions plots the confidence set
plot_grid <- function(indicator_array, lower_bds, upper_bds) {
  # get the dimensions
  n_rows <- nrow(indicator_array)
  n_cols <- ncol(indicator_array)

  # Calculate the width and height of each subdivided region
  width <- (upper_bds[1] - lower_bds[1]) / n_rows
  height <- (upper_bds[2] - lower_bds[2]) / n_cols

  # Create a data frame to store the rectangles
  rectangles <- data.frame(
    xmin = numeric(),
    xmax = numeric(),
    ymin = numeric(),
    ymax = numeric(),
    fill = character()
  )

  # Loop through the indicator array and create rectangles
  for (i in 1:n_rows) {
    for (j in 1:n_cols) {
      xmin <- lower_bds[1] + (i - 1) * width
      xmax <- xmin + width
      ymin <- lower_bds[2] + (j - 1) * height
      ymax <- ymin + height
      fill <- ifelse(indicator_array[i, j] == 1, "blue", "white")

      rectangles <- rbind(rectangles, data.frame(
        xmin = xmin,
        xmax = xmax,
        ymin = ymin,
        ymax = ymax,
        fill = fill
      ))
    }
  }

  # Plot the rectangles using ggplot2
  ggplot() +
    geom_rect(data = rectangles, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = fill), color = "black") +
    scale_fill_identity() +
    theme_minimal() +
    labs(x = "X", y = "Y") +
    coord_fixed(ratio = 1)
}
